services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: "racing_engine"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./deployments/init_db:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432